### ISSUE TITLE
Add helper text to Create Campaign screen to instruct novice users

### ISSUE THREAD

**Issue by wesrowe** [helloGov/webapp#145]
Under the label for each field (Script, Thank You Message, Learn More URL) needs some explanation of what it means.

**Comment by jordeguevara** [comment]
taking a look at this issue

**Comment by kbertash** [comment]
Okay so after some feedback and discussion (thanks!) 

Campaign Title: "Ex: 'Vote YES on SB280.'"

Script: No helper text needed but please change section title to "Call Script"

Thank you message: "Appears after a call is made."

Learn more URL: "Link to a page on your org's website about the issue."
