### ISSUE TITLE
Success message for campaign list "Link" button

### ISSUE THREAD

**Issue by wesrowe** [helloGov/webapp#149]
**Current state**: The "Link" button on the campaign list copies the link to the user's clipboard. But the user doesn't know this happened.
**Desired state**: Implement a Bootstrap alert to notify the user that "Success: Link copied to clipboard."

**Comment by jordeguevara** [comment]
haven't played with the css, but I came up two possible notifications 

1. Bootstrap alert under the Copy URL button 
<img width="1674" alt="screen shot 2019-01-15 at 9 46 25 am" src="https://user-images.githubusercontent.com/34716202/51200682-0c869200-18af-11e9-913f-93a2ad382b14.png">

2. HTML in the Copy URL button button 
<img width="1583" alt="screen shot 2019-01-15 at 10 17 40 am" src="https://user-images.githubusercontent.com/34716202/51200715-24f6ac80-18af-11e9-8712-1b930d69bf22.png">

Both appear when users clicks button

**Comment by kbertash** [comment]
I like the success notification that appears underneath. Thanks for your work on this.

**Comment by nowfred** [comment]
Is there a reason this is implemented specifically as a bootstrap/jquery modal as opposed to a regular angular modal? If there is can merge at will, bringing in those libs for a modal seems like overkill

**Comment by seport** [comment]
resolved in #273
