### ISSUE TITLE
Set up cloud dev environment 

### ISSUE THREAD

**Issue by wesrowe** [helloGov/webapp#150]
- [x] Select cloud platform for app
- [x] Set up build pipeline from GitHub
- [x] Configure super-admin for team's use

**Comment by Reltre** [comment]
Just to lay out my plan for this task. 

### Database

I think I'm going to try and set up mongodb stitch and have our application access that db server. We can use dedicated add-ons with Heroku, but they all cost money per month. The former option is a pay as much as you use option.

### Pipeline

Heroku has Heroku pipelines, which allow us to easily setup up multiple application instances together. At the moment, we just need to authorize access to our GH organization to finish this step.

**Comment by Reltre** [comment]
Checklist item number 3 should be complete once helloGov/deploy#9 is merged.

**Comment by Reltre** [comment]
I've enabled automatic deploys on Heroku from the master branch. We should test this out to see if everything is hooked up correctly.

**Comment by nowfred** [comment]
This is happening, closing
