### ISSUE TITLE
Add basic analytics to Campaign list page (Pageviews, Calls) and hide Analytics button

### ISSUE THREAD

**Issue by wesrowe** [helloGov/webapp#151]
The Analytics page currently only has two numbers on it. A whole page isn't even necessary. 
Just put the two numbers on the campaign list in columns toward the right.

**Comment by jschnapper** [comment]
I can pick this up! I don't have access to assign myself

**Comment by jschnapper** [comment]
Hey all, sorry for being totally unresponsive -- wasn't cool of me. But thanks @seport for picking this up and fixing everything
