### ISSUE TITLE
List of campaign page for a influencer

### ISSUE THREAD

**Issue by WCRest** [helloGov/webapp#16]
Create a page displaying a list of the following for each campaign. Mockup attached. 
	 - date_created
	 - title
	 - analytics: links to /campaign/analytics/{{campaign_id}}
	 - edit: links to /campaign/edit/{{campaign_id}}
	 - delete: links to /campaign/delete/{{campaign_id}}

Expect a list of objects containing:
	 - date_created
	 - title
         - campaign_id

	 
![image](https://cloud.githubusercontent.com/assets/970117/21706077/224c01f6-d379-11e6-9df3-4eaa7bd6d30b.png)

**Comment by WCRest** [comment]
You can access our current implementation of this at

**Comment by seport** [comment]
@kate-rose is this done?
