### ISSUE TITLE
Setup build process for Heroku pipeline

### ISSUE THREAD

**Issue by Reltre** [helloGov/webapp#171]
We can either use a `Procfile` for this or buildpacks and a `heroku.yml` file or an `app.json` file.
Here are some resources:

1. [build packs](https://devcenter.heroku.com/articles/buildpack-builds-heroku-yml)
2. [Procfile](https://devcenter.heroku.com/articles/procfile)

**Comment by nowfred** [comment]
@Reltre this is done right? I see the Procfile in the repo

**Comment by Reltre** [comment]
@nowfred yea, this is done now
