### ISSUE TITLE
Follower App Usability - Address Page

### ISSUE THREAD

**Issue by wesrowe** [helloGov/webapp#172]
- [x] (In chrome on Mac) The only way (9 times out of 10) to “accept” one of the addresses that the type-ahead provides is to 1) press down-arrow to highlight the address, and 2) hit Enter. Hitting Tab didn’t work, it un-focuses the form field and leaves behind only the characters I actually typed (after an instant flash of the whole address). Clicking with the mouse on one of the addresses exhibits same behavior. (Note: Every once in a while Tab or mouse-click _did_ work as expected.)
  -->_Need to test mobile to see if tapping address has same usability issue as mouse click._
- [ ] Back button usability - Pressing Back button anywhere in Follower app should return user to previous screen in Follower app. Current behavior: Back from any page ( tries to navigate browser to page _before_ helloGov was opened. E.g., the new-tab view in Chrome. (I wasn't able to reproduce exactly what would happen if a Follower link was opened from another web page, hence the Back button would be disabled due to no history.)
- [ ] Pressing Enter in address form field should click Submit. (Check with UX designer?) (Same behavior for mobile touch-keyboard?)
- [ ] Hover state of Submit button actually makes it look disabled - in lightening the font only (no change to button color) it actually appears to gray-out the text, looking disabled.
- [ ] Add field validation so that only a full street address is accepted. Zip codes and city names are not enough info to accurately pull your representatives.

**Comment by tpetersen0308** [comment]
Also add address validation for full state address (street, city, state, zip), with meaningful feedback when a field is missing.
