### ISSUE TITLE
Add Campaign Title to Follower UI landing page

### ISSUE THREAD

**Issue by wesrowe** [helloGov/webapp#173]
UX enhancement for the "Enter Address" screen. 

**AS A** Follower of an organization
**WHEN** I click the campaign short-link (e.g. facebook, email)
**I WANT TO** see the title of the Campaign above the address field to remind me why I'm being asked for my address.

Note: UX design needed

**Comment by Vallsurf** [comment]
I think this ties into a much needed improvement for campaigns - some sort of "info" section that describes the purpose of the campaign, along with a little bit more verbose instructions. If we feel this is something that would be useful, we can create a separate issue. Either way, I'm happy to grab this one in the mean time.

**Comment by kbertash** [comment]
After consulting with some of our orgs who volunteered to test, re: branding, having the name of the organization and the same kind of logo that they already use for ex: Facebook, Twitter, is just enough personalization for them.

**Comment by wesrowe** [comment]
Thanks for the user research, Kate!

**Comment by kbertash** [comment]
Should probably add some copy over it. 
"Follow these steps to make your voice heard on this important issue."
[Campaign Title]

**Comment by Jeremy-D** [comment]
is this sort of what we're going for?

![Screen Shot 2019-04-18 at 8 48 10 PM](https://user-images.githubusercontent.com/24968759/56404410-6040a880-621b-11e9-8b38-82b422a652a5.png)

**Comment by treyfour** [comment]
@Jeremy-D Looks Great!  Kate's good with this for MVP.  
We may have copy tweaks later, but we're in a great place.  Thank you!
@kbertash
