### ISSUE TITLE
Analytics Front end

### ISSUE THREAD

**Issue by WCRest** [helloGov/webapp#19]
For a given campaign we need to display:

- Calls made
 - Page views
 - % of viewer who called
 - graph page views to calls
 - breakdown of the same information by social platform

When an influencer navigates to /analytics/{{campaign_id}}, they will see a page mocked up below:
![image](https://cloud.githubusercontent.com/assets/970117/21739459/42f1042e-d450-11e6-9438-7b45ac1af873.png)
![image](https://cloud.githubusercontent.com/assets/970117/21739463/5eb9993c-d450-11e6-9cd6-9e547440ff50.png)

Currently, this page is generated by /app/views/analytics.hbs. Edit this file to structure and style the analytics data.

**Comment by seport** [comment]
This has been implemented in the MVP to display number of page views and number of hits but we should consider more detailed analytics for future versions.
