### ISSUE TITLE
Pop-up confirmation on Delete Campaign button

### ISSUE THREAD

**Issue by kbertash** [helloGov/webapp#190]
Adds a confirmation that the organization would like to delete the campaign after the "delete" button is clicked to prevent accidental clicks.

AS AN organization
WHEN I am on the campaigns dashboard and click the delete button
I WANT TO see a confirmation pop-up that reads, "This will permanently delete this campaign and any associated link will no longer work."
I WANT TO see below that text, a "Yes, delete my campaign" and "Cancel" buttons.

**Comment by jordeguevara** [comment]
here is modal that pop up when delete is clicked.

There seems to be some css overrides, haven't had a chance to look at the custom css 

another possible catch would be to disable the button and add a check box that would enable it

<img width="836" alt="screen shot 2019-01-15 at 9 31 29 pm" src="https://user-images.githubusercontent.com/34716202/51228336-fe675e80-190c-11e9-8404-3cdd1d5aadc5.png">



<img width="642" alt="screen shot 2019-01-15 at 9 30 51 pm" src="https://user-images.githubusercontent.com/34716202/51228358-1a6b0000-190d-11e9-96a1-a4c3dbab5397.png">
