### ISSUE TITLE
UI Accessibility Fixes to Follower UI

### ISSUE THREAD

**Issue by kate-rose** [helloGov/webapp#216]
- [ ] Change background to white and text to dark teal on all Follower UI Screens
- [ ] Fix Analytics screen colors so it's still usable

Follower Script Screen (after entering address and hitting submit)
- [ ] Increase size of font in Sample Script text. 
- [ ] Add helper text above the Sample Script text box, "You can use this sample script for your call."

**Comment by wesrowe** [comment]
I investigated the styles - the follower UI styles are tightly coupled to the Campaigns styles, as the green b.g. is on <body>.
Easy way:
 - change rules on <body>, which globally changes Campaign screens also
 - wrecks Analytics page, but other campaign screens do fine (used white divs for most of UI anyway)

Hard way:
	- refactor html to create containers for different app areas

**Comment by seport** [comment]
seems like this was addressed in #225
