### ISSUE TITLE
Invalid CSS properties in follower script page header

### ISSUE THREAD

**Issue by ahrGNUts** [helloGov/webapp#220]
I was looking at the follower script page header and noticed some invalid CSS applied to the header text. Properties in question shown with arrows ( <--- ):

.section-header {
    font-size: 1.1em;
    text-transform: uppercase;
    font-weight: medium; <---
    letter-spacing: .2; <---
}

I think these are supposed to be are `font-weight: bold` and `letter-spacing: .2em`.
Which one do you guys like better?

Current version:
![invalid props](https://user-images.githubusercontent.com/5104274/57171679-5eeeae80-6dcb-11e9-8289-b5af9aebcdcb.png)

Updated properties:
![valid props](https://user-images.githubusercontent.com/5104274/57171684-7fb70400-6dcb-11e9-85b5-1082123a334e.png)

**Comment by seport** [comment]
@kate-rose and I looked at it and decided to go with the third option of bold font weight and no letter spacing 🕶 
I can make a quick PR for it now :)
