### ISSUE TITLE
Tab Keystroke From Campaign Title to Legislature Level

### ISSUE THREAD

**Issue by treyfour** [helloGov/webapp#227]
Tab keystroke should go from Campaign title to Legislative level.

AS A: registered user (schultetrevor)
WHEN I: Press the tab key on campaign title to go to the next field, it goes to “script”.
I WANT TO: Tab after I complete Campaign title to go to the next field (checkboxes for Legislature level).

**Comment by ahrGNUts** [comment]
@treyfour confirmed behavior on Safari. Firefox, Chrome, and Opera all work according to your specs as-is.

If a user checks one of the checkboxes and the drop-down list appears, should the focus then move to the dropdown or go directly to the script input?

**Comment by treyfour** [comment]
Ah, I see it does work on Chrome but I was testing on safari in which it doesn't.  (interesting that's a feature by default)

If a user checks one of the checkboxes and the drop-down list appears, the **focus should go to the dropdown** as that's a required field.

I think we should add the tab indexes.   
I tend to accidentally skip that field when I'm filling out the form, and I've heard that from other users also.
