### ISSUE TITLE
"I'm Done" button missing copy

### ISSUE THREAD

**Issue by kate-rose** [helloGov/webapp#235]
I'm Done button missing text and both buttons not wrapping/mobile responsive. See screenshot below.

**Comment by kate-rose** [comment]
Hmm, looks like the copy is missing on desktop too:

<img width="614" alt="Screen Shot 2019-05-20 at 8 32 08 PM" src="https://user-images.githubusercontent.com/19698792/58066645-0b0bf580-7b3f-11e9-86a7-57f17be63b22.png">

**Comment by wesrowe** [comment]
@kate-rose -- Did you say you saw this blank button in Production? It's not showing up in my local version. 
If it's still a problem in Prod please share a shortlink so I can investigate.

**Comment by ahrGNUts** [comment]
@kate-rose, @wesrowe  -- I looked into it and the copy isn't actually missing, it's just being rendered white so it blends with the background of the button. For some reason Safari is interpreting our CSS a bit different than the other browsers (assuming Kate is using Safari for these screenshots). Opened #239 to fix

**Comment by kate-rose** [comment]
Because project boards are wacky, pull request for this issue (thanks @ahrGNUts!) is here: https://github.com/helloGov/webapp/projects/2#card-22189384
