### ISSUE TITLE
Buttons not mobile UI responsive

### ISSUE THREAD

**Issue by kate-rose** [helloGov/webapp#236]
Mobile UI is not wrapping buttons and their text properly. See screenshot.
![IMG_8046](https://user-images.githubusercontent.com/19698792/58064186-f8d98980-7b35-11e9-83cf-1edb68897383.jpeg)

**Comment by kate-rose** [comment]
Also happening on follower screens:
![Image-1](https://user-images.githubusercontent.com/19698792/58112759-fcf2bf00-7ba8-11e9-8acd-230bbe4eaf1e.jpeg)

**Comment by wesrowe** [comment]
@kate-rose - 2 separate clarifications:
1) campaigns page icons - what layout were you expecting? (e.g., all 4 icons in one row). I believe they should also have an outline/box around them to make the separation of list items clearer.
2) Buttons on mobile - I'm thinking shrink the font a bit. Also thinking the script font and other fonts could come down a bit.

**Comment by wesrowe** [comment]
![image](https://user-images.githubusercontent.com/4054752/58298410-39344400-7d90-11e9-8e94-101688c411cd.png)
Fonts are pretty out of whack - the button fonts are enormous now (on my local).
