### ISSUE TITLE
Add "learn more" link to Campaign landing page

### ISSUE THREAD

**Issue by kate-rose** [helloGov/webapp#256]
AS A follower
WHEN I click on a campaign
I WANT TO see a learn more link that opens the webpage that was configured as the "learn more link" by the campaign creator in a new window. 

See mockup below:

<img width="552" alt="learnmorelink" src="https://user-images.githubusercontent.com/19698792/59241885-56ee0f80-8bbe-11e9-9351-dbd23f08b156.png">

**Comment by dwgillette** [comment]
Submitted pull request. Let me know if there are any issues! @kate-rose

**Comment by seport** [comment]
resolved in #264
