### ISSUE TITLE
Follower Landing Page, backend

### ISSUE THREAD

**Issue by billkee** [helloGov/webapp#26]
After clicking on a campaign URL, the follower sees a landing page asking for street address, with Google address autocomplete. The street address will be used to look up the right representative.

Scope: mobile Design updates, connect to influencer. Out of scope: Desktop, it will exist but design will not be refined.

Back/Front end: 5-10 hrs

Total time: 1 week

**Comment by seport** [comment]
@kate-rose I think this is done
