### ISSUE TITLE
Follower Call Page, frontend

### ISSUE THREAD

**Issue by billkee** [helloGov/webapp#27]
After entering street address, follower needs to know which congressperson they are going to call, and see the script and 'more info' link

This is the core CTA page for the follower, where they see who they need to call and about what

Page that shows:
- Name of congressperson
- Picture
- Script
- More Info Link
- "Call" button, which has the right number for the congressperson

**Comment by Dfenestrator** [comment]
This is pretty much done except for the "more info" button.
