### ISSUE TITLE
New user signup timing out on server

### ISSUE THREAD

**Issue by kate-rose** [helloGov/webapp#294]
When the new user receives their link to sign up, and attempts to complete the signup workflow, the page freezes for 30-60 seconds after hitting "submit," and they receive the following error:

<img width="573" alt="Screen Shot 2019-09-09 at 8 34 10 PM" src="https://user-images.githubusercontent.com/19698792/64582077-5857e100-d341-11e9-8e36-5bd17c38c4a3.png">

**Comment by seport** [comment]
addressed already in #292
