### ISSUE TITLE
Fit the custom URL completely onto a mobile screen

### ISSUE THREAD

**Issue by greenhacks** [helloGov/webapp#309]
**AS A** user testing submitting the signup form in a mobile environment (Apple iOS 13.1.3) with a link provided to a gmail account
**WHEN I** reach the custom URL page
**I WANT TO** see the custom URL fit on my mobile screen.

Currently, the URL is cut off, and I am not able to scroll over to see the entire URL

![HelloGov_custom URL](https://user-images.githubusercontent.com/29167127/69117291-1388ae80-0a44-11ea-8176-6c3d31932344.PNG)

**Comment by ldaws003** [comment]
@greenhacks Seems like a simple change to the css could fix this. Mind if I work on it?
