### ISSUE TITLE
Display phone number on campaign call page

### ISSUE THREAD

**Issue by Dfenestrator** [helloGov/webapp#52]
Right now we have a call button but no display for the phone number in case the user wants to make the call manually. Should we add this? (should be straightforward, just need a small design change on that page)

The disadvantage is that we can't track users who do this, but this seems to be a minor tradeoff.

**Comment by rachelcolby11** [comment]
Good point - I think it would be good to have this. Not sure how we're implementing analytics but might it also be feasible to have a button for the user to click saying "I made the call manually" so the call could still be tracked?
