### ISSUE TITLE
Allow organizations to upload a logo

### ISSUE THREAD

**Issue by Dfenestrator** [helloGov/webapp#55]
Right now it's Shaun King for everyone, we should change this to be stored as part of their login, or display nothing. We need to add the image to the influencer data store in Mongo for this (or link to it somewhere - maybe with a pic collection by UserID).

**Comment by kbertash** [comment]
AS the organization
WHEN I set up my account
I WANT to upload a 360 pixel by 360 pixel photo.

This will eventually be displayed on the follower-side view of a campaign, will put that on a different issue. 

Questions: what kind of image size validation is easiest to implement?
