### ISSUE TITLE
Avoid comments?

### ISSUE THREAD

**Issue by aab29** [helloGov/webapp#6]
First, some background on me.  👱 I'm a big fan of Robert C. Martin's book [Clean Code](https://books.google.com/books/about/Clean_Code.html?id=dwSfGQAACAAJ).  📖 I highly recommend it to anyone who writes code on computers, and that's where most of my (sometimes counter-intuitive) ideas originate--in case you were wondering.  🖥 

One of the main ideas presented by the book is that code should be optimized to be readable by humans, and not necessarily by computers.  👀  You'd think that a good way to achieve this would be to leave a comment after every line of code to explain what it's doing, but in practice that actually tends to cause problems.  🔨  That's because code is constantly changing, and when code changes, it's easy to forget to update a comment, which leads to comments that lie.  🤥 🔥 

The solution that the book recommends (and which I also prefer) is to make code self-explanatory with descriptive class/variable/method naming.  📛  So each class should have a name that explains exactly what its responsibility is.  🎓  Each method of the class should have a name that describes exactly what it does and *why*.  🐃 ❓  And each variable name should explain what value it holds.  🌵  Sometimes names have to become pretty verbose to express specific ideas, but that's not a problem for modern computers, so we shouldn't be afraid to make our names as long as they need to be.  ✍️ 

It can be tricky to express everything that you'd normally express in a comment through the names in the code itself, but I always try my hardest to first and then leave comments only as a last resort.  🌴

I realize the ideas here might be controversial, so feel free to dispute them.  ☝️ I don't want to dictate any of our code conventions, but I would like to start a conversation over them.  😅

**Comment by WCRest** [comment]
I strongly support self-explanatory code. I find that if comments are necessary to explain a piece of code, something can probably be done to make the code simpler and more readable.

**Comment by seport** [comment]
![why not both?](https://i.imgur.com/s4eamxv.jpg)

Why not both? I think code should absolutely be descriptive on its own, but now that this project is in the hands of Hack for LA, I'm anticipating lots of new programmers coming through the codebase. A short one line description of what's going on can be really helpful to new developers no matter how descriptive your code is. I don't think it's necessary to comment every single line of code, but wherever code starts getting a little unconventional or lofty it can't hurt to leave a quick explanation as to what you were thinking at the time. If you're worried about stale comments, maybe we can create a PR review checklist that includes making sure any comments in the changed files still reflect what the code does?

**Comment by seport** [comment]
We will write descriptive code but will use comments with discretion.
