### ISSUE TITLE
Move TODOs to issues in issue-tracking system?

### ISSUE THREAD

**Issue by aab29** [helloGov/webapp#7]
This is closely-related to https://github.com/helloGov/singleAction/issues/6 .  📜  I've found that leaving `TODO` comments in code makes it difficult to track them.  🔍  It also gives them a tendency to lie as they become outdated, just like any other comment in code.  🤥  Of course issues can become outdated in issue-tracking systems as well, but at least there project managers and other non-programmers can see them too, so everyone's aware of them.  👃  And they won't get paved-over and become permanent parts of the software.  🛤

**Comment by aab29** [comment]
Sounds cool!  I've never seen something like that in action, but I'm certainly down to give it a try.  🏇 😎

**Comment by seport** [comment]
The hook sounds cool, but could be overkill. If someone wants to set it up I'm not against it, but maybe we can start by creating a PR template to remind people to convert TODOs to issues?

**Comment by seport** [comment]
We will use issues instead of TODO comments, but we will not use a commit hook for now.
