### ISSUE TITLE
Avoid abbreviations?

### ISSUE THREAD

**Issue by aab29** [helloGov/webapp#9]
I know this one tends to bug people a lot, so feel free to shoot it down if you hate it.  🛩 

I managed to get most people on board with this one at the last place I worked, and I felt like it helped us avoid a lot of confusion.  But at the same time, I recognize that lots of people would consider it *extremely* picky.  👃 

The theory is that programmers started abbreviating variable names back in the early days of computers, when most languages had a character limit for variable names due to limited system resources.  At this point computers are more than powerful enough to handle variable names of any length, but abbreviations in code remain commonplace.  ⚾️  Most programmers assume that abbreviating will save them time, especially for names that have to be typed frequently.  🐄 🐄 🐄  I'd contend that that assumption is usually wrong.  🐱 

Even the longest variable names can be typed within a few seconds, and with modern IDE tools like autocomplete, time spent typing is generally negligible.  Time spent reading, on the other hand, is very important to consider.  ✋  It's important to remember that code gets read much more often than it gets written.  📚  But the real slowdown usually comes when somebody new has to read your code for the first time, and they can't figure out what an abbreviation stands for.  ⌛️  Another big time-sink can be trying to remember how you/another programmer abbreviated a particular word when you typed it originally.  🐢  (Was it `ColMgr` or `ClrMgr` or did I actually write out `ColorManager` or what?) 🎨 

Soooo... to keep things simple, I try to write out full words in my code whenever possible.  I won't make you do it if you don't want to, but I figured I'd at least throw it out there.  🏈 😄

**Comment by seport** [comment]
I'm here for it! I'd love to get a code styleguide going and I would love to document this decision if others agree ✋

**Comment by seport** [comment]
Let's make an issue to add a styleguide (airbnb maybe??)
